### ISSUE TITLE
UnboundLocalError: local variable 'color' referenced before assignment

### ISSUE THREAD

**Issue by VGKintsugi** [doyousketch2/SatRGB#1]
```
Decoding  BG_CE.DG2   DGT2 PP - Packed Pixel data 
Traceback (most recent call last):
  File "./satrgb.py", line 644, in <module>
    main()
  File "./satrgb.py", line 637, in main
    convert( obj, outputdir )
  File "./satrgb.py", line 155, in convert
    fifteenbit  = format( color, '0>16b' )
UnboundLocalError: local variable 'color' referenced before assignment
```

**Comment by VGKintsugi** [comment]
I believe the fix is to change line 155 to
``
        fifteenbit  = format( sixteenbit, '0>16b' )
``

**Comment by doyousketch2** [comment]
k, I'll look at it.  Haven't looked at that code in a while, but that might be.  What game was it, Sonic Jam?

**Comment by VGKintsugi** [comment]
Yes, Sonic Jam. I tested the fix out, PNGs look correct now.

**Comment by doyousketch2** [comment]
Yea I think yer right.  I'll try it out in a little while.

**Comment by VGKintsugi** [comment]
No worries. It's a cool script.

**Comment by doyousketch2** [comment]
Updated code.  Also put quotes around filenames, so parentheses don't throw errors.  Lemme know if it runs OK for ya, or if I made any other dumb typos.

**Comment by VGKintsugi** [comment]
Something is off: 

``
  File "./satrgb.py", line 418
    elif ext:
       ^
SyntaxError: invalid syntax
``

**Comment by doyousketch2** [comment]
on the same file?  BG_CE.DG2

**Comment by doyousketch2** [comment]
Oh yer right.  Hmm, it ran just a second ago.  Think I screwed up the tabs.  Used to Lua at the moment where whitespace isn't important.  Will update again in a min.
